version: "3.9"
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - CSV_PATH=/data/product_catalog.csv
      - NAME_COL=name
    volumes:
      - ./data:/data:ro
    ports:
      - "8000:8000"
    depends_on:
      - ollama

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    environment:
      - OLLAMA_BASE=http://ollama:11434/v1
      - OLLAMA_KEY=ollama
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - BACKEND_URL=http://backend:8000
    ports:
      - "8501:8501"
    depends_on:
      - backend
      - ollama

volumes:
  ollama:
